INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(1, SYSDATE, '디지털기기', 1, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(2, SYSDATE, '생활가전', 2, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(3, SYSDATE, '가구/인테리어', 3, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(4, SYSDATE, '생활/주방', 4, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(5, SYSDATE, '유아용', 5, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(6, SYSDATE, '여성패션/잡화', 6, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(7, SYSDATE, '남성패션/잡화', 7, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(8, SYSDATE, '스포츠/레저', 8, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(9, SYSDATE, '취미/게임/음반', 9, 1);

INSERT INTO CATEGORIES (CATEID, REGDT, CATENM, ORDERNO, USE) VALUES
(10, SYSDATE, '도서', 10, 1);

